### ISSUE TITLE
semop: nsops désigne le nombre opérations, et non le nombre de sémaphores concernés

### ISSUE THREAD

**Issue by sandhose** [pdav/ens#4]
Extrait du manuel:

https://github.com/pdav/ens/blob/4ddbdde35b839f4010c4a11b0669557e37b2046e/manuel/manuel.tex#L3801-L3804

Or, d'après `SEMOP(2)` (version du manuel BSD du 22 septembre 1995), *“The length of sops is indicated by nsops.”*. De ce que je comprend, on peut exécuter plusieurs opérations sur le même sémaphore dans un même appel de `semop`, donc `nsops` ne désigne pas *forcément* le nombre de sémaphores concernées.

La phrase d'après (*« Le tableau `sops` (de `nsops` éléments)… »*) est donc correcte.

**Comment by pdav** [comment]
Merci pour la précision !
